[package]
name = "etl-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
derive_builder = "0.20.2"
flume = "0.11.1"
futures = "0.3.31"
tokio = {version = "1.48.0", features = ["full"]}
tokio-util = "0.7.17"
